# See the documentation for more information:
# https://packit.dev/docs/configuration/

actions:
    changelog-entry:
        - bash -c 'echo "- New upstream release"'
    post-upstream-clone:
        - wget https://src.fedoraproject.org/rpms/rust-openssh-keys/raw/rawhide/f/rust-openssh-keys.spec

specfile_path: rust-openssh-keys.spec

upstream_tag_template: v{version}

# add or remove files that should be synced
files_to_sync:
    - .packit.yaml
    - rust-openssh-keys.spec 

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: openssh-keys   
# downstream (Fedora) RPM package name
downstream_package_name: rust-openssh-keys

jobs: 

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-all